# Generated by Django 3.0.4 on 2020-04-04 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('tipo_item', models.TextField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('nome_cliente', models.TextField(blank=True, max_length=100, null=True)),
                ('data_aluguel', models.DateTimeField(verbose_name='Data do Aluguel')),
                ('data_criacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
